services: 
    web-server:
      image: nginx:1.21.1
      container_name: web-nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
      networks:
        - web-dev
      volumes:
        - ./confs/servers/:/etc/nginx/conf.d/
        - ./projects:/var/www/projects

    php:
      build:
        dockerfile: ./php.dockerfile
        context: .
      image: php:8.2-fpm
      container_name: web-php
      restart: always
      volumes: 
        - ./projects:/var/www/projects
      ports: 
        - "9000:9000"
      networks: 
        - web-dev

    # PHPMyAdmin
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      container_name: web-admin
      restart: always
      ports:
        - 81:80
      environment:
        PMA_HOST: db
      networks:
        - web-dev

    db:
      image: mysql:8.0.33
      container_name: web-mysql
      restart:  always
      volumes: 
        - ./confs/mysql_db:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: mydb
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass
      ports:
        - "3306:3306"
      networks: 
        - web-dev

networks: 
      web-dev:
        driver: bridge
